// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modelos;

#nullable disable

namespace Modelos.Migrations
{
    [DbContext(typeof(ContextoConversor))]
    partial class ContextoConversorModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entidades.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Persona");

                    b.HasData(
                        new
                        {
                            id = 1,
                            FechaNacimiento = new DateTime(2003, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sandra",
                            Telefono = "638354533",
                            UserName = "Sandra",
                            apellido = "Jimenez",
                            password = "1234567"
                        },
                        new
                        {
                            id = 2,
                            FechaNacimiento = new DateTime(1990, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "pepe",
                            Telefono = "63234233",
                            UserName = "Pepe",
                            apellido = "Jimenez",
                            password = "1234567"
                        },
                        new
                        {
                            id = 3,
                            FechaNacimiento = new DateTime(1945, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            Telefono = "638234533",
                            UserName = "Juan",
                            apellido = "Jimenez",
                            password = "1234567"
                        },
                        new
                        {
                            id = 4,
                            FechaNacimiento = new DateTime(2006, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Andres",
                            Telefono = "63567533",
                            UserName = "Andres",
                            apellido = "Jimenez",
                            password = "1234567"
                        },
                        new
                        {
                            id = 5,
                            FechaNacimiento = new DateTime(2008, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Fernando",
                            Telefono = "632344533",
                            UserName = "Fernando",
                            apellido = "Jimenez",
                            password = "1234567"
                        },
                        new
                        {
                            id = 6,
                            FechaNacimiento = new DateTime(2001, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Jose",
                            Telefono = "634324533",
                            UserName = "Jose",
                            apellido = "Jimenez",
                            password = "1234567"
                        },
                        new
                        {
                            id = 7,
                            FechaNacimiento = new DateTime(1983, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Dani",
                            Telefono = "634324533",
                            UserName = "Dani",
                            apellido = "Jimenez",
                            password = "1234567"
                        },
                        new
                        {
                            id = 8,
                            FechaNacimiento = new DateTime(1995, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laura",
                            Telefono = "631234567",
                            UserName = "Laura",
                            apellido = "Gomez",
                            password = "1234567"
                        },
                        new
                        {
                            id = 9,
                            FechaNacimiento = new DateTime(1987, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos",
                            Telefono = "636789012",
                            UserName = "Carlos",
                            apellido = "Perez",
                            password = "1234567"
                        },
                        new
                        {
                            id = 10,
                            FechaNacimiento = new DateTime(1993, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Isabel",
                            Telefono = "639567890",
                            UserName = "Isabel",
                            apellido = "Lopez",
                            password = "1234567"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
